apiVersion: app.fybrik.io/v1alpha1
kind: FybrikApplication
metadata:
  name: hello-world-read-module-test
spec:
  selector:
   workloadSelector:
     matchLabels: {
       app: notebook
     }
  appInfo:
    purpose: Fraud Detection
    role: Data Owner
  data:
    - dataSetID: "default/medals-winners"
      requirements:
        interface:
          protocol: s3
          dataformat: csv
    - dataSetID: "default/bank"
      requirements:
        interface:
          protocol: s3
          dataformat: csv