apiVersion: app.m4d.ibm.com/v1alpha1
kind: M4DApplication
metadata:
  name: hello-world-read-module-test
spec:
  selector:
   workloadSelector:
     matchLabels: {
       app: notebook
     }
  appInfo:
    purpose: Fraud Detection
    role: Data Owner
  data:
    - dataSetID: "{\"ServerName\":\"mds1\",\"AssetGuid\":\"806d357c-86da-422a-890e-7ac3998a7f1d\"}"
      requirements:
        interface:
          protocol: s3
          dataformat: csv