# Default values for hello-world-module job.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

global:
  environment: []

replicaCount: 1

## Module image
image: 
  repository: ghcr.io/mohammad-nassar10/hello-world-read-module 
  tag: latest
  pullPolicy: IfNotPresent
  pullSecret: null

imagePullSecrets: []

# Action (copy/read)
read:
- assetID: "test1"
  # Read source
  source:
    connection:
      name: s3
      s3:
        bucket: cloud-object-storage-l4-cos-standard-7vz
        endpoint: s3.us-east.cloud-object-storage.appdomain.cloud
        object_key: data.csv
      type: 2
    credentialLocation: htttp://test/test
    format: csv

nameOverride: ""
fullnameOverride: ""

## Job configurations
#backoffLimit: 4
#restartPolicy: Never

serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: ""
service:
  type: ClusterIP
  port: 80
annotations: {}

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi
